### Criar um novo parque
POST https://cantinhodocerrado-backend-4a23f7315303.herokuapp.com/parques
Content-Type: application/json

{
"nome": "Parque TESTE",
"descricao": "É um parque natural municipal que foi criado no dia 07 de novembro de 1997, sob o decreto nº 7452. Situado no bairro Santa Luzia, no Setor Sul de Uberlândia. Sua finalidade é preservar a fauna e a flora, proporcionar lazer público e promover atividades de cunho educacional e científico. Por ser uma Unidade de Conservação de Proteção Integral, é proibida qualquer tipo de exploração dos recursos naturais dentro do seu limite. Inclusive, no seu interior, está localizado o Córrego Lagoinha, que é um dos afluentes urbanos do Rio Uberabinha, o principal rio que abastece a cidade.",
"localizacao": {
        "latitude": -18.93939069822312,
        "longitude": -48.237909769504654
    },
"estadoConservacao": "O Parque Santa Luzia apresenta uma rica avifauna, com espécies endêmicas do Cerrado e até ameaçadas de extinção, a exemplo do mutum-de-penacho (Crax fasciolata fasciolata), ponto que reforça a importância fundamental desta Unidade de Conservação na área urbana de Uberlândia. A área do parque é limpa e bem cuidada, com destaque para a jardinagem e paisagismo. O local possui muitas árvores, em meio a espécies nativas e exóticas, assim como plantas ornamentais. Também contém vários pontos para descanso e contemplação da paisagem.",
"tamanhoArea": 26.83,
"horarioVisitacao": {"horarioPorDia": {"Terça-feira": "08:00-17:30","Quarta-feira": "08:00-17:30","Quinta-feira": "08:00-17:30","Sexta-feira": "08:00-17:30","Sábado": "08:00-17:30","Domingo": "08:00-17:30","Feriados": "08:00-17:30"}},
"atrativosTuristicos": "Trilha Ecológica Ferreirinha, Casa da Árvore, Jardim dos Ipês, Labirinto de Hibisco, Sala Verde",
"educacaoAmbiental": true,
"dificuldadeTrilhas": "Leve",
"banheiros": true,
"bebedouro": true,
"acessibilidade": "Rampas e corrimãos apenas no acesso à área central do parque",
"estacionamento": false,
"contato": "(34) 3225-0076",
"redesSociais": "https://www.instagram.com/professor.angoti/, https://twitter.com/parquesantaluzia,https://youtube.com/parquesantaluzia",
"demaisInformacoes": "O território do parque é dividido por duas ruas, o que forma três fragmentos de remanescentes florestais do bioma Cerrado, cuja cobertura vegetal é composta por veredas e uma mata de galeria que margeia o Córrego Lagoinha. Na periferia do fragmento intermediário existe uma lagoa artificial, possível de ser vista por quem transita perto do local. Entretanto, a primeira parte do parque, que também é a maior, é a única aberta para visitação.",
    
"fotos": [
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_155915569_HDR.jpg?alt=media&token=b3410615-8f91-49b3-b4c1-5d42b5066dda",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_143221016_HDR.jpg?alt=media&token=fedc270a-b547-4364-bd33-e1d09c49e628",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_093640236_HDR.jpg?alt=media&token=659f927d-1d64-4f5e-a44b-488ab0d2d137"
]}



    


### Listar todos os parques
GET https://cantinhodocerrado-backend-4a23f7315303.herokuapp.com/parques

### Obter um parque por ID
GET https://cantinhodocerrado-backend-4a23f7315303.herokuapp.com/parques/1

### Atualizar um parque existente
PUT https://cantinhodocerrado-backend-4a23f7315303.herokuapp.com/parques/10
Content-Type: application/json

{
  "horarioVisitacao": {
        "horarioPorDia": {
            "Segunda-feira": "07:00-19:00",
            "Terça-feira": "07:00-19:00",
            "Quarta-feira": "07:00-19:00",
            "Quinta-feira": "07:00-19:00",
            "Sexta-feira": "07:00-19:00",
            "Sábado": "07:00-19:00",
            "Domingo": "07:00-19:00"
        }
    },
}

### Deletar um parque por ID
DELETE https://cantinhodocerrado-backend-4a23f7315303.herokuapp.com/parques/18
