### Criar um novo parque
POST https://cantinhodocerrado-backend-4a23f7315303.herokuapp.com/parques
Content-Type: application/json

{
"nome": "Parque TESTE",
"descricao": "É um parque natural municipal que foi criado no dia 07 de novembro de 1997, sob o decreto nº 7452. Situado no bairro Santa Luzia, no Setor Sul de Uberlândia. Sua finalidade é preservar a fauna e a flora, proporcionar lazer público e promover atividades de cunho educacional e científico. Por ser uma Unidade de Conservação de Proteção Integral, é proibida qualquer tipo de exploração dos recursos naturais dentro do seu limite. Inclusive, no seu interior, está localizado o Córrego Lagoinha, que é um dos afluentes urbanos do Rio Uberabinha, o principal rio que abastece a cidade.",
"localizacao": {
        "latitude": -18.93939069822312,
        "longitude": -48.237909769504654
    },
"estadoConservacao": "O Parque Santa Luzia apresenta uma rica avifauna, com espécies endêmicas do Cerrado e até ameaçadas de extinção, a exemplo do mutum-de-penacho (Crax fasciolata fasciolata), ponto que reforça a importância fundamental desta Unidade de Conservação na área urbana de Uberlândia. A área do parque é limpa e bem cuidada, com destaque para a jardinagem e paisagismo. O local possui muitas árvores, em meio a espécies nativas e exóticas, assim como plantas ornamentais. Também contém vários pontos para descanso e contemplação da paisagem.",
"tamanhoArea": 26.83,
"horarioVisitacao": {"horarioPorDia": {"Terça-feira": "08:00-17:30","Quarta-feira": "08:00-17:30","Quinta-feira": "08:00-17:30","Sexta-feira": "08:00-17:30","Sábado": "08:00-17:30","Domingo": "08:00-17:30","Feriados": "08:00-17:30"}},
"atrativosTuristicos": "Trilha Ecológica Ferreirinha, Casa da Árvore, Jardim dos Ipês, Labirinto de Hibisco, Sala Verde",
"educacaoAmbiental": true,
"dificuldadeTrilhas": "Leve",
"banheiros": true,
"bebedouro": true,
"acessibilidade": "Rampas e corrimãos apenas no acesso à área central do parque",
"estacionamento": false,
"contato": "(34) 3225-0076",
"redesSociais": "https://www.instagram.com/professor.angoti/, https://twitter.com/parquesantaluzia,https://youtube.com/parquesantaluzia",
"demaisInformacoes": "O território do parque é dividido por duas ruas, o que forma três fragmentos de remanescentes florestais do bioma Cerrado, cuja cobertura vegetal é composta por veredas e uma mata de galeria que margeia o Córrego Lagoinha. Na periferia do fragmento intermediário existe uma lagoa artificial, possível de ser vista por quem transita perto do local. Entretanto, a primeira parte do parque, que também é a maior, é a única aberta para visitação.",
    
"fotos": [
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_155915569_HDR.jpg?alt=media&token=b3410615-8f91-49b3-b4c1-5d42b5066dda",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_143221016_HDR.jpg?alt=media&token=fedc270a-b547-4364-bd33-e1d09c49e628",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_093640236_HDR.jpg?alt=media&token=659f927d-1d64-4f5e-a44b-488ab0d2d137"
]}


### Listar todos os parques
GET https://cantinhodocerrado-backend-4a23f7315303.herokuapp.com/parques

### Obter um parque por ID
GET https://cantinhodocerrado-backend-4a23f7315303.herokuapp.com/parques/1

### Atualizar um parque existente
PUT https://cantinhodocerrado-backend-4a23f7315303.herokuapp.com/parques/13
Content-Type: application/json

{
  "horarioVisitacao": "Entrada franca.Terça a domingo e feriados (08h às 17h30). Limitada a entrada de visitantes até às 15h."
}

### Deletar um parque por ID
DELETE https://cantinhodocerrado-backend-4a23f7315303.herokuapp.com/parques/14





# dados dos parques

### Parque Victório Siquierolli
POST https://cantinhodocerrado-backend-4a23f7315303.herokuapp.com/parques
Content-Type: application/json

{
 "nome": "Parque Victório Siquierolli",
 "descricao": "É um parque natural municipal que foi criado no dia 05 de março de 2000, pelo decreto nº 8166, por um convênio entre a Prefeitura Municipal de Uberlândia (PMU) e o Fundo Nacional de Meio Ambiente (FNMA) (Uberlândia, 2000). O Parque Siquierolli é um parque urbano, localizado no Setor Norte, no bairro Jardim América. A vegetação é composta por formações florestais do bioma Cerrado, com presença de espécies nativas e exóticas, e áreas em processo de regeneração natural.",
 "localizacao": {
        "latitude": -18.8726494018131,
        "longitude": -48.28460761361053
    },
"estadoConservacao": "Como o Parque Siquierolli é uma Unidade de Conservação (UC) de Proteção Integral, desde a sua criação não há mais impactos antrópicos que causam a supressão da vegetação, a exceção são as queimadas que ocorrem na vizinhança e se alastram parque adentro, pois apenas alambrados delimitam a área.",
"tamanhoArea": 23.23,
"horarioVisitacao" : "Entrada franca. Terça a domingo e feriados (08h às 17h30).",
"atrativosTuristicos": "Museu de Biodiversidade do Cerrado, Trilha do Óleo, Casa-de-pau-a-pique, Teatro a céu aberto, Monjolo, Sala verde, Parque infantil",
"educacaoAmbiental": "Visitas ao Museu de Biodiversidade do Cerrado e à Trilha do Óleo. É necessário agendamento para atendimento monitorado.",
"dificuldadeTrilhas": "Leve. A “Trilha do Óleo” possui distância total de 1,3 Km e um trajeto que abrange trechos de  Cerradão, a Mata  de  Galeria  ao  redor  do  Córrego  Liso  e  áreas  que  estão  em  sucessão ecológica. O terreno é plano, não exige conhecimento técnico ou experiência prévia, e o percurso pode ser realizado por pessoas com qualquer nível de condicionamento físico e crianças a partir da pré-escola.",
"banheiros": true, "bebedouro": true, "estacionamento": true,   
"acessibilidade": "Rampas e corrimãos apenas no acesso à área central do parque",
"contato": "Parque Siquierolli - (34) 3212-1692 / Museu de Biodiversidade do Cerrado - http://www.mbc.ib.ufu.br/",
"redesSociais": "Não possui",
"demaisInformacoes": "O percurso da “Trilha do Óleo” não exige significativo esforço físico do visitante devido às características apresentadas. Apesar disso, faltam sinalizações no decorrer do caminho que poderiam facilitar o entendimento do trajeto para visitantes novatos. Outro fator importante é a necessidade de indicações de relevo no solo nos locais sombreados, servindo como um auxílio ao deslocamento de idosos, pessoas com deficiência e seus acompanhantes. O reforço de cercas que circundam o Córrego Liso, por ser uma área de barranco, também se faz fundamental para garantir a segurança dos visitantes.",
 "fotos": [
         "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Victório%20Siquierolli%2FIMG_20210823_145831659_HDR.jpg?alt=media&token=dd8b8938-0d86-4c98-8939-3c82aff32c43",
         "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Victório%20Siquierolli%2FIMG_20210823_145806820_HDR.jpg?alt=media&token=f1f19e53-2198-4c54-bb50-2f91b3ae4242", 
         "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Victório%20Siquierolli%2FIMG_20210823_145730861_HDR.jpg?alt=media&token=38fa4a65-ea63-4199-9c22-8ea9a8fc8cb1", 
         "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Victório%20Siquierolli%2FIMG_20210823_145715908_HDR.jpg?alt=media&token=55ef6227-7cff-43b7-81a1-a8360e80c517", 
         "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Victório%20Siquierolli%2FIMG_20210823_145701756_HDR.jpg?alt=media&token=4ade06ea-55f2-4c18-96a3-d568b654b2c1",
         "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Victório%20Siquierolli%2FIMG_20210823_145608197_HDR.jpg?alt=media&token=60998c44-8ebe-4516-a98d-1f70c13695fd",
         "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Vict%C3%B3rio%20Siquierolli%2FIMG_20210823_145554036_HDR.jpg?alt=media&token=e19a7424-7f5f-490e-ba12-762c71d9b018",
         "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Victório%20Siquierolli%2FIMG_20210823_145510510_HDR.jpg?alt=media&token=9f3c5e4f-e16f-4a1f-9100-7435f13ffefb",
         "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Victório%20Siquierolli%2FIMG_20210823_145326452.jpg?alt=media&token=b0344a87-6931-43b6-9fd2-3af571ae58db",
         "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Victório%20Siquierolli%2FIMG_20210823_145301455_HDR.jpg?alt=media&token=8f248f70-af19-4b7f-9590-4dc6afb276c2",
         "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Victório%20Siquierolli%2FIMG_20210823_145123826.jpg?alt=media&token=3e66d5ba-448e-48e3-8a6b-c0b43f38760e",
         "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Victório%20Siquierolli%2FIMG_20210823_145059645.jpg?alt=media&token=349218f9-9ba9-407a-a836-c3d2e661e921",
         "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Vict%C3%B3rio%20Siquierolli%2FIMG_20210823_144856712.jpg?alt=media&token=1f948ba8-2521-4645-98e7-449642e12e76",
         "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Vict%C3%B3rio%20Siquierolli%2FIMG_20210823_144409314_HDR.jpg?alt=media&token=140ea3d7-a354-4d5a-b062-8454f00ed4c1",
	 "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Vict%C3%B3rio%20Siquierolli%2FIMG_20210823_131840862_HDR.jpg?alt=media&token=dd7b0a19-8df7-4c13-a9ac-231a8b5626ad",
         "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Vict%C3%B3rio%20Siquierolli%2FIMG_20210823_131826860_HDR.jpg?alt=media&token=1178d4cc-5cf1-4bfa-a421-d724832675a9"
]}



###Parque Santa Luzia
POST https://cantinhodocerrado-backend-4a23f7315303.herokuapp.com/parques
Content-Type: application/json

{
"nome": "Parque Santa Luzia",
"descricao": "É um parque natural municipal que foi criado no dia 07 de novembro de 1997, sob o decreto nº 7452. Situado no bairro Santa Luzia, no Setor Sul de Uberlândia. Sua finalidade é preservar a fauna e a flora, proporcionar lazer público e promover atividades de cunho educacional e científico. Por ser uma Unidade de Conservação de Proteção Integral, é proibida qualquer tipo de exploração dos recursos naturais dentro do seu limite. Inclusive, no seu interior, está localizado o Córrego Lagoinha, que é um dos afluentes urbanos do Rio Uberabinha, o principal rio que abastece a cidade.",
"localizacao": {
        "latitude": -18.93939069822312,
        "longitude": -48.237909769504654
    },
"estadoConservacao": "O Parque Santa Luzia apresenta uma rica avifauna, com espécies endêmicas do Cerrado e até ameaçadas de extinção, a exemplo do mutum-de-penacho (Crax fasciolata fasciolata), ponto que reforça a importância fundamental desta Unidade de Conservação na área urbana de Uberlândia. A área do parque é limpa e bem cuidada, com destaque para a jardinagem e paisagismo. O local possui muitas árvores, em meio a espécies nativas e exóticas, assim como plantas ornamentais. Também contém vários pontos para descanso e contemplação da paisagem.",
"tamanhoArea": 26.83,
"horarioVisitacao": "Entrada franca.Terça a domingo e feriados (08h às 17h30)",
"atrativosTuristicos": "Trilha Ecológica Ferreirinha, Casa da Árvore, Jardim dos Ipês, Labirinto de Hibisco, Sala Verde",
"educacaoAmbiental": true,
"dificuldadeTrilhas": "Leve",
"banheiros": true,
"bebedouro": true,
"acessibilidade": "Rampas e corrimãos apenas no acesso à área central do parque",
"estacionamento": false,
"contato": "(34) 3225-0076",
"redesSociais": "Não possui",
"demaisInformacoes": "O território do parque é dividido por duas ruas, o que forma três fragmentos de remanescentes florestais do bioma Cerrado, cuja cobertura vegetal é composta por veredas e uma mata de galeria que margeia o Córrego Lagoinha. Na periferia do fragmento intermediário existe uma lagoa artificial, possível de ser vista por quem transita perto do local. Entretanto, a primeira parte do parque, que também é a maior, é a única aberta para visitação.",   
"fotos": [
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_155915569_HDR.jpg?alt=media&token=b3410615-8f91-49b3-b4c1-5d42b5066dda",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_155045363_HDR.jpg?alt=media&token=be50cd84-c69a-4ad6-8df4-95d78a829b6d",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_154423194_HDR.jpg?alt=media&token=dddcd7f1-555b-4ad8-9b15-a6741154310f",      
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_154041411_HDR.jpg?alt=media&token=1e42cac5-1b2a-4d88-9b91-2357713d6aa5",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_150951564_HDR.jpg?alt=media&token=79c57415-9d0e-4a88-9dff-e9faa2a2ec59",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_150913997_HDR.jpg?alt=media&token=32dff9d7-0b26-4d8c-86d3-2aa651f3025c",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_150336502_HDR.jpg?alt=media&token=3a57738c-05bd-409d-9d8a-9b435d91d19c",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_150146336_HDR.jpg?alt=media&token=def85638-6d87-44f1-b9f0-db3d6251b1bb",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_145758391_HDR.jpg?alt=media&token=94ec1c22-527f-47eb-9e15-85854375261f",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_145217428_HDR.jpg?alt=media&token=49be50b9-6a00-4e39-b561-d432e2362797",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_144810079_HDR.jpg?alt=media&token=15489d8a-5e88-4910-b31a-481abea079fb",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_144624255_HDR.jpg?alt=media&token=ae434413-6a22-4ce0-b221-a1a81b696656",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_144511057.jpg?alt=media&token=e8b9d606-b6bb-444e-af0f-145aa42eada7",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_143221016_HDR.jpg?alt=media&token=fedc270a-b547-4364-bd33-e1d09c49e628",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Santa%20Luzia%2FIMG_20210825_093640236_HDR.jpg?alt=media&token=659f927d-1d64-4f5e-a44b-488ab0d2d137"
]}



###Parque Gávea
POST https://cantinhodocerrado-backend-4a23f7315303.herokuapp.com/parques
Content-Type: application/json

{
"nome": "Parque Gávea",
"descricao": "O parque foi criado em 2012, como uma medida de compensação ambiental pelas obras residências dos condomínios Gávea Park e Solares da Gávea, empreendimentos construídos pelas empresas Empreendimentos S/A e Realiza Construtora Ltda. Localizado no Setor Sul, no bairro Morada da Colina, o local abriga uma parte do Córrego Vinhedo, que faz parte da Bacia Hidrográfica do Rio Uberabinha. É o único parque que permite o acesso de cães acompanhados de seus tutores.",
"localizacao": {
        "latitude": -18.954476870153076,
        "longitude": -48.27999664943001
},
"estadoConservacao": "A cobertura vegetal, na sua maior parte, acompanha toda a extensão da Área de Preservação Permanente (APP) do Córrego Vinhedo, caracterizada como mata de galeria. A composição florística é formada por espécies nativas e exóticas.",
"tamanhoArea": 19.05,
"horarioVisitacao": "Entrada franca.Terça a domingo e feriados (08h às 17h30)",
"atrativosTuristicos": "Museu DICA (Diversão com Ciência e Arte), Trilha do Sistema Solar, Praças temáticas, como a da Tabela Periódica, Parque infantil, Academia ao ar livre",
"educacaoAmbiental": false,
"dificuldadeTrilhas": "Leve",
"banheiros": true,
"bebedouro": true,
"acessibilidade": "Rampas e corrimãos apenas no acesso à área central do parque",
"estacionamento": true,
"contato": "(34) 3230-9517",
"redesSociais": "https://www.instagram.com/parquegavea/",
"demaisInformacoes": "Apesar da fundação do Parque Gávea visar a conservação dos recursos naturais e propiciar atividades educacionais, científicas e recreativas, o espaço ainda não possui uma regulamentação legal como uma Unidade de Conservação, via decreto, a exemplo dos parques Siquierolli e Santa Luzia. Por conta da sua beleza cênica, o local também é muito frequentado por fotógrafos amadores e profissionais.",
"fotos": [
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Gávea%2FIMG_20210827_103347883.jpg?alt=media&token=1b649fa6-cafc-41dd-9b7e-69a0439ccb24",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Gávea%2FIMG_20210827_105430940.jpg?alt=media&token=8bc66633-fe6f-4063-b329-4a160d746e03",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/G%C3%A1vea%2FIMG_20210827_105007353_HDR.jpg?alt=media&token=fe01569b-3060-4d66-adaa-9fcc633067f0",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/G%C3%A1vea%2FIMG_20210827_104925697_HDR.jpg?alt=media&token=23f80c8e-bed3-4339-8636-3d5e95fb32f9",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/G%C3%A1vea%2FIMG_20210827_104824404.jpg?alt=media&token=199087fa-9228-4c24-8e3e-12ebe9e36a2b",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/G%C3%A1vea%2FIMG_20210827_104533813.jpg?alt=media&token=f13d0be6-f36c-497b-b0c7-bdd044b73309",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/G%C3%A1vea%2FIMG_20210827_104505192_HDR.jpg?alt=media&token=43f75000-b187-4eee-8205-f56fb10021ca",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/G%C3%A1vea%2FIMG_20210827_104408452_HDR.jpg?alt=media&token=4d05b45a-5c52-40ef-a76a-51eb46b32b97",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/G%C3%A1vea%2FIMG_20210827_104230430_HDR.jpg?alt=media&token=e32e4bc7-86d6-43c7-af8f-21079a861948",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/G%C3%A1vea%2FIMG_20210827_104152190_HDR.jpg?alt=media&token=b766f23e-0292-4c9d-935a-641d69df9658",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/G%C3%A1vea%2FIMG_20210827_104136074_HDR.jpg?alt=media&token=885f67da-f406-447d-a1b0-4c7c7967ca64",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/G%C3%A1vea%2FIMG_20210827_104046339.jpg?alt=media&token=bea216ed-41d9-4e0e-9ad0-5afeaaaf3da5",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/G%C3%A1vea%2FIMG_20210827_103808309_HDR.jpg?alt=media&token=b8d839bc-8d7c-443f-863a-8a732b1bd273",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/G%C3%A1vea%2FIMG_20210827_103524133.jpg?alt=media&token=620c4d05-7745-494f-aee3-7b4981648a18",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/G%C3%A1vea%2FIMG_20210827_103452919_HDR.jpg?alt=media&token=8de13bb5-e01d-4b78-810a-36259a0ee268",
"https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/G%C3%A1vea%2FIMG_20210827_103419886.jpg?alt=media&token=acaecb4d-b267-47cd-badb-83ff56600df5"
]}



###Parque Estadual do Pau Furado
POST https://cantinhodocerrado-backend-4a23f7315303.herokuapp.com/parques
Content-Type: application/json

{
        "nome": "Parque Estadual do Pau Furado",
        "descricao": "O Parque Estadual do Pau Furado é a primeira Unidade de Conservação de Proteção Integral do Triângulo Mineiro, criado sob o decreto estadual de 27 de janeiro de 2007, como medida de compensação ambiental pela construção das Usinas Hidrelétricas Capim Branco I e II. Seu território abrange os municípios de Uberlândia e Araguari.",
        "localizacao": {
                "latitude": -18.828363132279105,
                "longitude": -48.167493274526414
        },
        "estadoConservacao": "O Parque Estadual do Pau Furado é de relevante importância para a conservação da biodiversidade no Triângulo Mineiro, região onde o Cerrado está altamente ameaçado pelas atividades agropecuárias em larga escala, urbanização e incêndios criminosos. O parque contém catalogadas 932 espécies de animais e plantas, sendo algumas delas ameaçadas de extinção, como o lobo-guará (Chrysocyon brachyurus).",
        "tamanhoArea": 2186.85,
        "horarioVisitacao": "Entrada franca. Terça a domingo e feriados (08h às 17h30). Limitada a entrada de visitantes até às 15h.",
        "atrativosTuristicos": "Mirante, Cachoeira do Marimbondo, Cachoeira Terra Branca, Prainha, Curral de Pedras",
        "educacaoAmbiental": true,
        "dificuldadeTrilhas": "Moderada a moderada superior",
        "banheiros": true,
        "bebedouro": true,
        "acessibilidade": "Rampas e corrimãos apenas no acesso à área central do parque",
        "estacionamento": true,
        "contato": "(34) 3232-5622",
        "redesSociais": "https://www.instagram.com/paufurado/",
        "demaisInformacoes": "Conta com atividades de ciclismo e observação da vida silvestre mediante agendamento.",
        "fotos": [
                "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Pau%20Furado%2FIMG-20241113-WA0018.jpg?alt=media&token=d087fe68-0e5e-45c6-9019-ff05fb6a1c2f",
                "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Pau%20Furado%2FIMG-20241113-WA0023.jpg?alt=media&token=8ddd5653-65af-48ad-ad70-54d54ea313f4",
                "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Pau%20Furado%2FIMG-20241113-WA0022.jpg?alt=media&token=5846d4a8-ce81-44fc-8e65-26487d671438",
                "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Pau%20Furado%2FIMG-20241113-WA0021.jpg?alt=media&token=b4a0cbf9-5a17-4688-8174-49af27430c38",
                "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Pau%20Furado%2FIMG-20241113-WA0020.jpg?alt=media&token=ca6f7667-747a-4737-a434-806f6f93839c",
                "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Pau%20Furado%2FIMG-20241113-WA0019.jpg?alt=media&token=43464943-f4ba-4d00-8cef-c71d17e12a0f",
                "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Pau%20Furado%2FIMG-20241113-WA0017.jpg?alt=media&token=679c20df-ca2d-4d22-900c-d54ff0a1d381",
                "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Pau%20Furado%2FIMG-20241113-WA0016.jpg?alt=media&token=1f655250-e991-47d2-b59b-5f9333570520",
                "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Pau%20Furado%2FIMG-20241113-WA0015.jpg?alt=media&token=ca514361-3d15-464e-9566-d633fa192550",
                "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Pau%20Furado%2FIMG-20241113-WA0013.jpg?alt=media&token=4bd59411-9232-462e-8204-04e52e81aedb",
                "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Pau%20Furado%2FIMG-20241113-WA0012.jpg?alt=media&token=5a80c5cc-74c0-4007-baa8-f533e1179c3c",
                "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Pau%20Furado%2FIMG-20241113-WA0011.jpg?alt=media&token=13d96a0a-47c0-463a-89f5-43075cd661f3",
                "https://firebasestorage.googleapis.com/v0/b/cantinho-do-cerrado.appspot.com/o/Pau%20Furado%2FIMG-20241113-WA0010.jpg?alt=media&token=090c2f29-053a-4383-8533-403b7141ea39"  
        ]
}
